// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL2Ip5pWYp_fYqAmtivEzJo9oneJvAugM',
    appId: '1:603256103060:web:e878bfed99081b8d73d481',
    messagingSenderId: '603256103060',
    projectId: 'defender-f572a',
    authDomain: 'defender-f572a.firebaseapp.com',
    storageBucket: 'defender-f572a.appspot.com',
    measurementId: 'G-RDLTHQ0CMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVsYhtzGMzxHGATIXRAH17HyQcbIkVOaA',
    appId: '1:603256103060:android:16e76cd49646a78373d481',
    messagingSenderId: '603256103060',
    projectId: 'defender-f572a',
    storageBucket: 'defender-f572a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiP1RoiCqhCjRUNTjjI11fhzFALYrFbqw',
    appId: '1:603256103060:ios:d323af2db2822f3673d481',
    messagingSenderId: '603256103060',
    projectId: 'defender-f572a',
    storageBucket: 'defender-f572a.appspot.com',
    androidClientId: '603256103060-1d27p8evjpf451focls1sub86j0e96vl.apps.googleusercontent.com',
    iosClientId: '603256103060-ioq2ar2snhhkmmsrmm1u5mtg9itqrmm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.defender',
  );
}
